{"uuid": "7ea374a0-5b22-4154-b08f-126874ea114c", "children": ["0494303a-6335-4a2a-a44c-27e09f8cc1a5"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"/Users/natashamiadelets/Desktop/tms1_onl/venv/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/natashamiadelets/Desktop/tms1_onl/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/natashamiadelets/Desktop/tms1_onl/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/natashamiadelets/Desktop/final_task/diplom_nm/conftest.py\", line 13, in browser\n    browser = webdriver.Chrome(chrome_options=chrome_options)\n  File \"/Users/natashamiadelets/Desktop/tms1_onl/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"/Users/natashamiadelets/Desktop/tms1_onl/venv/lib/python3.9/site-packages/selenium/webdriver/common/service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1632744644652, "stop": 1632744644661}], "start": 1632744644652, "stop": 1632744644793}